Add Empty cache support
astarte-platform/astarte-device-sdk-esp32 pull request #116
Opened 2023-04-03 14:10 UTC by harlem88

The MQTT library sets a clean session by default, but we want to change this behavior by disabling it.
[mqtt-espidf - disable_clean_session](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/mqtt.html#_CPPv4N24esp_mqtt_client_config_t9session_t21disable_clean_sessionE)

Closes #115.

2023-04-03 14:29 UTC, rbino requested changes
I see a couple of problems here:
- First, `send_emptycache` is never called, while it should be called in the `on_connected` callback, after `send_introspection`.
- Second, I'm not 100% sure that disabling clean session in the current state of the SDK is the right thing to do, but this is more a "are we sure? let's reason about the corner cases" rather than a "don't do this"

2023-04-03 14:42 UTC, harlem88 commented
> I see a couple of problems here:
> 
> * First, `send_emptycache` is never called, while it should be called in the `on_connected` callback, after `send_introspection`.

Yes right, my error I had left it out after testing the release1-0.

> * Second, I'm not 100% sure that disabling clean session in the current state of the SDK is the right thing to do, but this is more a "are we sure? let's reason about the corner cases" rather than a "don't do this"

If you don't disable it, the field session_present passed in `on_connected` function will  always be `0`, and the empty_cache ( also introspection and subscription) will be resent on every connection.

2023-04-05 16:59 UTC, rbino approved these changes

2023-04-06 14:54 UTC, sorru94 approved these changes

2023-04-06 15:54 UTC, merged