Add unit tests on target/host
astarte-platform/astarte-device-sdk-esp32 pull request #140
Opened 2023-06-14 16:23 UTC by sorru94

2023-07-05 14:33 UTC, harlem88 requested changes
Add  `Check clang formatting`  on `unit_tests` folder.

2023-07-05 14:33 UTC, harlem88 commented on .github/workflows/unit.yaml
> +    container: espressif/idf:release-v5.0
```suggestion
    container: espressif/idf:release-v5.0.2
```

2023-07-06 07:48 UTC, harlem88 commented on .github/workflows/unit.yaml
> +    container: espressif/idf:release-v5.0
sorry, this is `espressif/idf:v5.0.2`

2023-07-06 08:16 UTC, harlem88 commented on .github/workflows/unit.yaml
> +    container: espressif/idf:release-v5.0
use `idf:release-v5.0`.

2023-07-06 08:51 UTC, harlem88 commented
About folder naming, what do you think about renaming to :
- `unit_tests` -> `tests`
- `host_and_target` -> `generic`, `all_targets`
- `host_prj` -> `host_app`

2023-07-06 08:54 UTC, sorru94 commented
> About folder naming, what do you think about renaming to :
> 
>     * `unit_tests` -> `tests`
> 
>     * `host_and_target` -> `generic`, `all_targets`
> 
>     * `host_prj` -> `host_app`

The choice of the name `unit_tests` was mostly because I was hoping to have another folder in the future for end-to-end tests, but it's probably too early for that.
'generic' looks good and 'host_app' also.

2023-07-06 12:45 UTC, harlem88 commented
> > About folder naming, what do you think about renaming to :
> > ```
> > * `unit_tests` -> `tests`
> > 
> > * `host_and_target` -> `generic`, `all_targets`
> > 
> > * `host_prj` -> `host_app`
> > ```
> 
> The choice of the name `unit_tests` was mostly because I was hoping to have another folder in the future for end-to-end tests, but it's probably too early for that. 'generic' looks good and 'host_app' also.

Looking in the different folders of  [esp-idf/components](https://github.com/espressif/esp-idf/tree/master/components/efuse)  you can always find a couple of `test_host` and `test_apps`, perhaps this should also be a potential folder structure.

2023-07-06 14:23 UTC, harlem88 approved these changes

2023-07-06 14:25 UTC, merged