Fix readability magic numbers
astarte-platform/astarte-device-sdk-esp32 pull request #176
Opened 2023-07-28 13:34 UTC by sorru94

2023-10-31 16:44 UTC, harlem88 requested changes

2023-10-31 16:44 UTC, harlem88 commented on src/uuid.c
> +#define UUID_TIME_HI_AND_VERSION_MASK_VERSION (0xF000U)
It seems unused, is it necessary?

2023-11-08 16:48 UTC, sorru94 commented on src/uuid.c
> +#define UUID_TIME_HI_AND_VERSION_MASK_VERSION (0xF000U)
Nope, can be removed

2023-11-09 11:18 UTC, harlem88 approved these changes

2023-11-09 11:18 UTC, merged