Change astarte_device_add_interface API
astarte-platform/astarte-device-sdk-esp32 pull request #66
Opened 2021-04-20 16:27 UTC by rbino

Pass a pointer to an `astarte_interface_t` struct. This allows to cleanup subscriptions, subscribing only to server owned interfaces (see https://github.com/astarte-platform/astarte/issues/568).

2021-04-20 16:28 UTC, rbino commented
cc @SuMere

2021-04-20 17:19 UTC, bettio requested changes

2021-04-20 17:19 UTC, bettio commented on include/list.h
> +/***************************************************************************
We should either rename it to astarte_list or make it a private header.

2021-04-20 17:19 UTC, bettio commented on include/list.h
> +static inline int list_is_empty(struct list_head_t *list_item)
let's use bool here (and we need to include `stdbool.h`).

2021-04-20 17:19 UTC, bettio commented on include/astarte_interface.h
> +    OWNERSHIP_DEVICE, /**< Device owned interface */
OWNERSHIP_DEVICE = 1, so 0 stands for invalid

2021-04-20 17:19 UTC, bettio commented on include/astarte_interface.h
> +    TYPE_DATASTREAM, /**< Datastream interface */
TYPE_DATASTREAM = 1, so 0 stands for invalid

2021-04-20 17:19 UTC, bettio commented on include/astarte_device.h
> +#include <astarte_interface.h>
Let's decide if we want to use `" "` or `< >`.

2021-04-20 17:19 UTC, bettio commented on CHANGELOG.md
> +- `astarte_device_add_interface` API change, the caller now has to provide a pointer to an
let's write `**incompatible API change**`

2021-04-21 10:14 UTC, bettio requested changes

2021-04-21 10:14 UTC, bettio commented on astarte_device.c
> +    LIST_FOR_EACH(item, &device->interfaces_list)
MUTABLE_LIST_FOR_EACH, otherwise it might crash.

2021-04-21 10:24 UTC, bettio approved these changes

2021-04-21 10:24 UTC, merged