Add support to arrays
astarte-platform/astarte-device-sdk-esp32 pull request #79
Opened 2021-11-30 12:09 UTC by bettio

2021-11-30 23:46 UTC, harlem88 requested changes

2021-11-30 23:46 UTC, harlem88 commented on include/astarte_bson_types.h
> +#define BSON_TYPE_ARRAY     '\x03'
Change this in `#define BSON_TYPE_ARRAY     '\x04'`

2021-11-30 23:46 UTC, harlem88 commented on astarte_bson_serializer.c
> +        snprintf(key, 12, "%i", count);
Why use `count` here instead of `i`?

2021-11-30 23:46 UTC, harlem88 commented on astarte_bson_serializer.c
> +    astarte_byte_array_destroy(&array_ser);
Change this with `astarte_bson_serializer_destroy(&array_ser);`

2021-12-23 17:28 UTC, harlem88 approved these changes

2021-12-23 17:41 UTC, rbino approved these changes

2021-12-23 17:51 UTC, merged